site_name: 'ugo_r_doc'
site_url: 'https://ugoproto.github.io/ugo_r_doc/'
repo_name: 'ugo_r_doc' # see doc, for bitbucket, gitlab
repo_url: 'https://github.com/ugoproto/ugo_r_doc.git'
# include a link to the repository of your project 
# repository is hosted in a private environment, the service logo can be set explicitly by setting
# extra.repo_icon to github, gitlab or bitbucket
site_description: 'A R documentation website.'
site_author: 'Ugo Sparks'
copyright: '© Ugo Sparks'
google_analytics: 
  - 'UA-93008985-1'
  - 'auto'

theme: 
  name: 'material' # 'readthedocs'
  language: 'en'
  search:
    language: 'en, fr' 
## 'Volkorn' 'Libre Baskerville' 'Merriweather'
## https://fonts.google.com
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
## https://fonts.google.com
  palette:
    primary: 'blue'
    accent: 'red'
## red, pink, purple, deep purple, indigo, blue, light-blue, cyan, teal, green, light-green, lime, yellow, amber, orange, deep-orange, brown, grey and blue-grey
  logo:
    icon: 'layers'
## https://material.io/icons/
  favicon: 'img/favicon.ico' 
## default, assets/images/favicon.png
  feature:
    tabs: false 
## another layer on top of the main navigation for larger screens in the form of tabs.           
#    social:
#      - type: 'gitlab'
#        link: 'w'
#        type: 'twitter'
#        link: 'w'
#      - type: 'linkedin'
#        link: 'w'
#  disqus: 'your-shortname'
## https://disqus.com/
## repo_icon: 'github' # gitlab, bitbucket

#extra_css: 
#    - 'extra.css'
## in the docs
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

pages:
  - Home: 'index.md'
  - Basics:
    - R Cheat Sheets: 'R_CS.md'
    - An Introduction to R: 'An Introduction to R.md'
    - Le logiciel R, maitriser le langage, effectuer des analyses (bio)statistiques: 'Le logiciel R, maitriser le langage, effectuer des analyses (bio)statistiques.md'
    - Formulas in R: 'Formulas_in_R.md' 
    - Improved Codes: 'Improved_codes.md'
    - Intermediate R: 'Intermediate_R.md'
    - Intermediate R - The apply Family: 'Intermediate_R_-_The_apply_Family.md' 
  - RStudio:
    - Code & Plot Chunk Options: 'Code___Plot_Chunk_Options.md'
    - Working with the RStudio IDE: 'Working_with_RStudio_IDE.md'
  - Data Wrangling Snippets:
    - I/O Snippets & Cleaning: 'IO_snippets___Cleaning.md'
    - Reading Data into R with readr: 'Reading_Data_into_R_with_readr.md'
    - Data Analysis in R, the data.table Way: 'Data_Analysis_in_R,_the_data.table_Way.md'
    - Data Manipulation in R with dplyr: 'Data_Manipulation_in_R_with_dplyr.md'
  - Plot Snippets:
    - Plot Snippets for Exploratory (and some Explanatory) Analyses: 'Plot_snippets_-_Basics.md'
    - Plot Snippets - ggplot2: 'Plot_snippets_-_ggplot2.md'
    - Plot Snippets - ggvis: 'Plot_snippets_-_ggvis.md'
    - Plot Snippets - Colours: 'Plot_snippets_-_Colours.md'
  - Packages:
    - googleVis (embed HTML plots): 'googleVis.md'
    - gganimate: 'gganimate.md'
    - Fast-and-Frugal Decision Trees: 'Fast-and-Frugal_Decision_Trees_in_R_with_FFTrees.md'
    - Big Data Analysis with Revolution R Enterprise: 'Big_Data_Analysis_with_Revolution_R_Enterprise.md'
    - Time Series in R, The Power of xts and zoo: 'Time+Series+in+R+The+Power+of+xts+and+zoo.md'
    - Parallel computing in R: 'Parallel computing in R.md'
  - Other Snippets: 
    - Tables: 'Tables.md'
    - Embedding HTML into HTML: 'embedding.md'
    - Embedding Rmd into Rmd: 'embedding2.md'
    - Frequentist vs. Bayesian: 'Frequentist_Bayesian.md'
  - A Hands-on Introduction to Statistics with R:
    - Statistics with R, Course One, Introduction: 'A_Hands-on_Introduction_to_Statistics_with_R,_Course_One,_Introduction.md'
    - Statistics with R, Course Two, Student's t-test: 'A_Hands-on_Introduction_to_Statistics_with_R,_Course_Two,_Student_s_T-test.md'
    - Statistics with R, Course Three, Analysis of Variance: 'A_Hands-on_Introduction_to_Statistics_with_R,_Course_Three,_Analysis_of_Variance.md'
    - Statistics with R, Course Four, Repeated Measures ANOVA: 'A_Hands-on_Introduction_to_Statistics_with_R,_Course_Four,_Repeated_Measures_Anova.md'
    - Statistics with R, Course Five, Correlation and Regression: 'A_Hands-on_Introduction_to_Statistics_with_R,_Course_Five,_Correlation_and_Regression.md'
    - Statistics with R, Course Six, Multiple Regression: 'A_Hands-on_Introduction_to_Statistics_with_R,_Course_Six,_Multiple_Regression.md'
    - Statistics with R, Course Seven, Moderation and Mediation: 'A_Hands-on_Introduction_to_Statistics_with_R,_Course_Seven,_Moderation_and_Mediation.md'
    - Statistics with R, Notes: 'A_Hands-on_Introduction_to_Statistics_with_R,_Notes.md'

markdown_extensions:
  - def_list
## to make glossaries
  - fenced_code
## ```python, ~~~~python, ~~~{.python}
  - footnotes
## [^1]: Lorem ipsum
## [^2]:
##     Lorem ipsum 1 (multiline)
##
##     Lorem ipsum 2
  - tables
## |First Header  | Second Header|
## |------------- | -------------|
## |Content Cell  | Content Cell |
## |Content Cell  | Content Cell |
  - admonition 
## https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - codehilite(linenums=true)
## ```python hl_lines="1 2"
## a=1
## ```
## https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
  - meta
## https://python-markdown.github.io/extensions/meta_data/
## https://squidfunk.github.io/mkdocs-material/extensions/metadata/
  - nl2br
## break the line with a new line or return
  - sane_lists
## numbers vs. bullets
## https://python-markdown.github.io/extensions/sane_lists/
  - smarty
## additional characters: ' "  «  ... -- ---
## watch when copy-pasted
  - toc(title=CONTENT, permalink=true, anchorlink=false, baselevel=3)
## permalink link to a subpart of the document
## anchorlink causes all headers to link to themselves.
## https://python-markdown.github.io/extensions/toc/
## https://squidfunk.github.io/mkdocs-material/extensions/permalinks/
##
## Third Party Extensions: https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions
##
  - pymdownx.arithmatex
## extra_javascript, see below
  - pymdownx.betterem
## bold, italic, both
## https://facelessuser.github.io/pymdown-extensions/extensions/betterem/
  - pymdownx.caret
## ^^ ^^ underline
  - pymdownx.critic
## markup for commenting, correcting
  - pymdownx.details
## alike admonition, can be nested!
## https://facelessuser.github.io/pymdown-extensions/extensions/details/
  - pymdownx.emoji
## https://facelessuser.github.io/pymdown-extensions/extensions/emoji/
## https://www.emojicopy.com/
## :smile: :heart: :thumbsup:
  - pymdownx.inlinehilite
## https://facelessuser.github.io/pymdown-extensions/extensions/inlinehilite/
## `#!python `
#  - pymdownx.magiclink
## detects links in Markdown and auto-generates the necessary markup
  - pymdownx.mark
## == == highlight
  - pymdownx.smartsymbols
## https://facelessuser.github.io/pymdown-extensions/extensions/smartsymbols/
## +/-  -->  <--  <-->  =/=  1/4  1st 2nd
  - pymdownx.superfences
## nest code blocks under blockquotes
  - pymdownx.tasklist(clickable_checkbox=true)
## https://facelessuser.github.io/pymdown-extensions/extensions/tasklist/
## - [ ]  - [x]
  - pymdownx.tilde
## https://facelessuser.github.io/pymdown-extensions/extensions/tilde/
## ~~ ~~ crossover
  - pymdownx.keys
## https://facelessuser.github.io/pymdown-extensions/extensions/keys/
## ++ctrl+alt+delete++
## MORE
#  - pyembed.markdown
## videos
